/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Coupon = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'brand' : IDL.Text,
  'validUntil' : Time,
});
export const CouponStatus = IDL.Record({
  'redeemed' : IDL.Bool,
  'coupon' : Coupon,
});

export const idlService = IDL.Service({
  'addCoupon' : IDL.Func([Coupon], [], []),
  'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getCouponHistory' : IDL.Func([], [IDL.Vec(CouponStatus)], ['query']),
  'redeemCoupon' : IDL.Func([IDL.Text], [CouponStatus], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Coupon = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'brand' : IDL.Text,
    'validUntil' : Time,
  });
  const CouponStatus = IDL.Record({ 'redeemed' : IDL.Bool, 'coupon' : Coupon });
  
  return IDL.Service({
    'addCoupon' : IDL.Func([Coupon], [], []),
    'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getCouponHistory' : IDL.Func([], [IDL.Vec(CouponStatus)], ['query']),
    'redeemCoupon' : IDL.Func([IDL.Text], [CouponStatus], []),
  });
};

export const init = ({ IDL }) => { return []; };